
import { useState, useEffect } from 'react';
import DashboardLayout from '../components/DashboardLayout';
import api from '../api/axios';
import { toast } from 'react-toastify';
import {
    ClipboardDocumentListIcon,
    BeakerIcon,
    DocumentTextIcon,
    ArrowDownTrayIcon
} from '@heroicons/react/24/outline';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { useAuth } from '../context/AuthContext';

const MedicalRecords = () => {
    const { user } = useAuth();
    const [records, setRecords] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetchRecords();
    }, []);

    const fetchRecords = async () => {
        try {
            const response = await api.get('/appointments');
            // Filter for appointments that have medical details or are completed
            const medicalRecords = response.data.filter(apt =>
                apt.diagnosis || apt.medications || apt.notes || apt.status === 'completed'
            );
            setRecords(medicalRecords);
        } catch (error) {
            toast.error('Failed to fetch medical records');
        } finally {
            setLoading(false);
        }
    };

    const generatePDF = (record) => {
        const doc = new jsPDF();

        // --- Header ---
        doc.setFillColor(63, 81, 181); // Brand Color (Indigo/Blue)
        doc.rect(0, 0, 210, 40, 'F');

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.setFont('helvetica', 'bold');
        doc.text("SwasthSeva", 14, 20);

        doc.setFontSize(12);
        doc.setFont('helvetica', 'normal');
        doc.text("Official Medical Record & Prescription", 14, 30);

        doc.setFontSize(10);
        doc.text(`Date: ${record.date} | Time: ${record.timeSlot}`, 150, 20);

        // --- Doctor & Patient Info Section ---
        doc.setTextColor(0, 0, 0);
        let yPos = 50;

        // Validating available data to avoid "undefined" in PDF
        const docName = record.doctorName || "Unknown Doctor";
        const dept = record.department || "General";
        const patName = user.name || "Patient";
        const patEmail = user.email || "";

        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text("Doctor Details:", 14, yPos);
        doc.text("Patient Details:", 110, yPos);

        yPos += 7;
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text(`${docName}`, 14, yPos);
        doc.text(`Name: ${patName}`, 110, yPos);

        yPos += 5;
        doc.text(`Department: ${dept}`, 14, yPos);
        doc.text(`Email: ${patEmail}`, 110, yPos);

        // --- Medical Info ---
        yPos += 15;
        doc.setDrawColor(200, 200, 200);
        doc.line(14, yPos, 196, yPos); // Divider line
        yPos += 10;

        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text("Medical Diagnosis", 14, yPos);

        yPos += 7;
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        const diagnosis = record.diagnosis || "No diagnosis recorded.";
        const splitDiagnosis = doc.splitTextToSize(diagnosis, 180);
        doc.text(splitDiagnosis, 14, yPos);

        yPos += (splitDiagnosis.length * 5) + 5;

        // --- Medications Table ---
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text("Prescribed Medications", 14, yPos);
        yPos += 5;

        // Parse medications string into table rows if it's a string, or use as is
        // Assuming medications is a string like "Meds 1, Meds 2" for now, or we can make it a single row
        const medsData = record.medications ? [[record.medications, "As advised", "-"]] : [["No medications prescribed", "-", "-"]];

        autoTable(doc, {
            startY: yPos,
            head: [['Medication Name', 'Dosage / Instruction', 'Duration']],
            body: medsData,
            theme: 'grid',
            headStyles: { fillColor: [63, 81, 181] },
            styles: { fontSize: 10 },
        });

        // --- Suggestions / Notes ---
        let finalY = doc.lastAutoTable.finalY + 15;

        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text("Doctor's Notes & Suggestions", 14, finalY);

        finalY += 7;
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        const notes = record.notes || "No additional notes.";
        const splitNotes = doc.splitTextToSize(notes, 180);
        doc.text(splitNotes, 14, finalY);

        // --- Footer ---
        const pageHeight = doc.internal.pageSize.height;
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text("Generated by SwasthSeva Healthcare System", 14, pageHeight - 10);
        doc.text("This is a computer-generated document and does not require a physical signature.", 14, pageHeight - 6);

        // Save
        doc.save(`Medical_Record_${record._id}.pdf`);
    };

    const handleDownload = (record) => {
        // Placeholder for PDF download functionality
        toast.info(`Downloading record for ${record.date}...`);
        generatePDF(record); // Call the new PDF generation function
    };

    if (loading) {
        return (
            <DashboardLayout>
                <div className="flex justify-center items-center h-full">
                    <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-brand-600"></div>
                </div>
            </DashboardLayout>
        );
    }

    return (
        <DashboardLayout>
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
                <h1 className="text-3xl font-bold text-gray-900 mb-8">Medical Records</h1>

                {records.length === 0 ? (
                    <div className="text-center py-12 bg-white rounded-xl shadow-sm">
                        <ClipboardDocumentListIcon className="mx-auto h-12 w-12 text-gray-400" />
                        <h3 className="mt-2 text-sm font-semibold text-gray-900">No medical records found</h3>
                        <p className="mt-1 text-sm text-gray-500">Once your doctor adds medical details, they will appear here.</p>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {records.map((record) => (
                            <div key={record._id} className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden hover:shadow-md transition-shadow">
                                <div className="p-6">
                                    <div className="flex justify-between items-start mb-4">
                                        <div>
                                            <h3 className="text-lg font-bold text-gray-900">{record.doctorName}</h3>
                                            <p className="text-sm text-gray-500">{record.department} • {record.date}</p>
                                        </div>
                                        {/* Download button (placeholder) */}
                                        <button
                                            onClick={() => handleDownload(record)}
                                            className="text-gray-400 hover:text-brand-600 transition-colors"
                                            title="Download Record"
                                        >
                                            <ArrowDownTrayIcon className="h-5 w-5" />
                                        </button>
                                    </div>

                                    <div className="space-y-4">
                                        {record.diagnosis && (
                                            <div className="bg-blue-50/50 p-3 rounded-lg border border-blue-100">
                                                <div className="flex items-center gap-2 mb-1">
                                                    <ClipboardDocumentListIcon className="h-4 w-4 text-blue-600" />
                                                    <h4 className="text-sm font-semibold text-blue-900">Diagnosis</h4>
                                                </div>
                                                <p className="text-sm text-gray-700">{record.diagnosis}</p>
                                            </div>
                                        )}

                                        {record.medications && (
                                            <div className="bg-emerald-50/50 p-3 rounded-lg border border-emerald-100">
                                                <div className="flex items-center gap-2 mb-1">
                                                    <BeakerIcon className="h-4 w-4 text-emerald-600" />
                                                    <h4 className="text-sm font-semibold text-emerald-900">Medications</h4>
                                                </div>
                                                <p className="text-sm text-gray-700 whitespace-pre-line">{record.medications}</p>
                                            </div>
                                        )}

                                        {record.notes && (
                                            <div className="bg-amber-50/50 p-3 rounded-lg border border-amber-100">
                                                <div className="flex items-center gap-2 mb-1">
                                                    <DocumentTextIcon className="h-4 w-4 text-amber-600" />
                                                    <h4 className="text-sm font-semibold text-amber-900">Notes</h4>
                                                </div>
                                                <p className="text-sm text-gray-700">{record.notes}</p>
                                            </div>
                                        )}

                                        {!record.diagnosis && !record.medications && !record.notes && (
                                            <div className="text-center py-4 bg-gray-50 rounded-lg text-sm text-gray-500 italic">
                                                No specific medical details added yet.
                                            </div>
                                        )}
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </div>
        </DashboardLayout>
    );
};

export default MedicalRecords;
